name: Deploy ChatApp

on:
  push:
    branches: [master]
    tags: ['v*']

jobs:
  # Deploy backend to Render (via blueprint sync)
  deploy-server:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4
      
      - name: Trigger Render Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
